// mcp-roster.mjs — render the full MCP tool roster to docs/MCP-ROSTER.md.
//
// THE ONE PLACE to see every verb the doors offer (founder ask, 2026-08-19:
// "a single place where I can easily see the full roster of mcp verbs,
// ESPECIALLY the apex world and everything in it"). The door itself
// (tools/list) stays the runtime truth; this file is its readable rendering —
// regenerate in the commit that changes any tool:
//
//   node tools/mcp-roster.mjs
//
// The apex `world` verb's ACTION roster is dispatch-derived here (action →
// flat tool), with the caveat printed in the doc: the live per-standpoint
// action list (with class-mark blurbs and dials) is the bare `world` call's
// answer — actions appear because class marks grant them, and law can move.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const { TOOLS, WRITE_TOOLS } = await import("../src/mcp.mjs");
const { DISPATCHABLE, dispatchToolFor } = await import("../src/world-apex.mjs");

const fence = (s) => String(s ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
const firstSentences = (s, n = 2) => {
  const parts = String(s ?? "").split(/(?<=\.)\s+/);
  return parts.slice(0, n).join(" ");
};

const lines = [];
lines.push("# The MCP roster — every verb at the doors");
lines.push("");
lines.push("*GENERATED by `tools/mcp-roster.mjs` — regenerate in the commit that changes any tool. The door's own `tools/list` is the runtime truth; this page is its readable rendering.*");
lines.push("");
lines.push(`*${TOOLS.length} tools · rendered ${new Date().toISOString().slice(0, 10)}*`);
lines.push("");

// ── the apex first, since it is the door the founder asked after ───────────
lines.push("## The apex: `world` — one verb, and everything in it");
lines.push("");
lines.push("A bare `world` call (with `handle:`) answers where you stand, who is about, and **`actions:` — the live roster of every act your standpoint affords**, each with its class-mark blurb, dials, and fields. That live answer outranks this table: actions appear because class marks grant them, and law moves at crossings.");
lines.push("");
lines.push("The dispatch table (action → the flat tool that carries its arguments):");
lines.push("");
lines.push("| apex action | dispatches to |");
lines.push("|---|---|");
for (const a of DISPATCHABLE) lines.push(`| \`${a}\` | \`${dispatchToolFor(a) ?? "— (argument-free: do: performs it directly)"}\` |`);
lines.push("");

// ── the flat roster ─────────────────────────────────────────────────────────
lines.push("## The flat tools, whole");
lines.push("");
for (const t of TOOLS) {
  const badge = WRITE_TOOLS.has(t.name) ? " · **write (credentialed)**" : " · read";
  lines.push(`### \`${t.name}\`${badge}`);
  lines.push("");
  lines.push(firstSentences(t.description, 3));
  lines.push("");
  const props = t.inputSchema?.properties ?? {};
  const required = new Set(t.inputSchema?.required ?? []);
  const names = Object.keys(props);
  if (!names.length) { lines.push("*No arguments.*"); lines.push(""); continue; }
  lines.push("| field | type | notes |");
  lines.push("|---|---|---|");
  for (const k of names) {
    const p = props[k];
    const type = p.enum ? p.enum.map((v) => `\`${v}\``).join(" \\| ") : (p.type ?? "");
    const req = required.has(k) ? "**required** — " : "";
    lines.push(`| \`${k}\` | ${fence(type)} | ${req}${fence(firstSentences(p.description, 1))} |`);
  }
  lines.push("");
}

const out = join(here, "..", "docs", "MCP-ROSTER.md");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n") + "\n");
console.log(`wrote ${out} — ${TOOLS.length} tools, ${DISPATCHABLE.length} apex actions`);
